---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "jensen.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "jensen.name" . }}
spec:
  replicas: 1
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 -}}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ template "jensen.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "jensen.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret | default (include "jensen.fullname" .) }}
                  key: {{ .Values.secrets.discordTokenKey | default "discord-token" }}
            {{- if .Values.secrets.sentryDsnKey }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret | default (include "jensen.fullname" .) }}
                  key: {{ .Values.secrets.sentryDsnKey }}
            {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}